version: '2'

services:

  postgres:
    build: ./postgres/
    container_name: postgres
    expose:
      - "5432"


  pgadmin4:
    build: ./pgadmin4
    container_name: pgadmin4
    ports:
      - "1701:80"


  flask:
    build: ./flask
    container_name: flask
    ports:
      - "1702:5000"
    volumes:
      - "../flask_app_source:/opt/flask_app_source"
    depends_on:
      - postgres

